import styles from "./page.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "How Hacksnap selects stories, prepares briefs and reads Hacker News discussions.",
};

export default function AboutPage() {
  return (
    <article className={`detail ${styles.page}`}>
      <p className="channel-path">
        hacksnap / <span>about</span>
      </p>
      <h1>About Hacksnap</h1>
      <p>
        Hacksnap is an independent reader for AI stories on Hacker News. It pairs a short article
        brief with a summary of selected comments, so you can decide what to read in full.
      </p>

      <section aria-labelledby="sources-heading">
        <h2 id="sources-heading">Sources and summaries</h2>
        <p>
          Stories and comments come from Hacker News. When an external article can be retrieved,
          Hacksnap summarizes its text separately from the discussion. For HN text posts and
          articles it cannot retrieve, the brief is limited to the material available. External
          source domains link to the original articles; links beside discussion points lead to the
          HN comments used for those points.
        </p>
        <p>
          Briefs are generated by AI and can miss context or make mistakes. Check the original
          article and linked comments before relying on a claim. A story may appear before its
          summary is ready.
        </p>
      </section>

      <section aria-labelledby="discussion-coverage-heading">
        <h2 id="discussion-coverage-heading">Discussion coverage</h2>
        <p>
          Hacksnap excludes deleted, dead and empty comments, then selects comments from active
          branches within a size limit. It includes available parent comments when selecting a
          reply. Long articles and comment inputs may be shortened. The resulting brief covers a
          sample of the discussion, not every comment or a vote by the HN community.
        </p>
      </section>

      <section aria-labelledby="discussion-analysis-heading">
        <h2 id="discussion-analysis-heading">Discussion themes</h2>
        <p>
          Newly analyzed stories group the discussion into themes. Each theme summarizes a topic
          raised by the selected comments, with links to the source comments behind it.
        </p>
        <p>
          Themes describe the available sample. They are not an exhaustive ranking, a measure of
          correctness, or a vote by the HN community.
        </p>
        <p>
          Analysis time and coverage describe the discussion sample separately from the article
          brief. Older stories retain their original discussion summaries; this feature is not
          backfilled.
        </p>
      </section>

      <section aria-labelledby="story-order-heading">
        <h2 id="story-order-heading">Story order</h2>
        <p>
          Latest lists summarized AI stories by when they were added to Hacksnap, newest first.
          Topic feeds use the same order. Monthly archives keep older stories accessible. Hacker
          News points and comments describe the stored discussion activity and do not control the
          feed order.
        </p>
      </section>

      <section aria-labelledby="skepticism-heading">
        <h2 id="skepticism-heading">Skepticism</h2>
        <p>
          The legacy skepticism label is separate from explicit agreement. Low skepticism does not
          mean agreement. High means the sampled comments lean doubtful, critical or concerned about
          the story’s subject. Low includes mixed, neutral and positive reactions. This is a
          qualitative AI estimate from at most ten selected comments, separate from the broader
          sample used for the discussion brief. It is not a numeric score or a claim of consensus.
          When no usable comments are available, Hacksnap shows that instead of guessing.
        </p>
      </section>
      <section aria-labelledby="read-elsewhere-heading">
        <h2 id="read-elsewhere-heading">Read elsewhere</h2>
        <p>
          Follow the <a href="/feed.xml">RSS feed</a>.
        </p>
      </section>
    </article>
  );
}
